[build]
command = "next build"
publish = ".next"


[[plugins]]
package = "@netlify/plugin-nextjs"

# [[redirects]]
# from = "/_nextRuntimeV4ImageHandler"
# # replicate runtime V4 image handler
# # https://github.com/netlify/next-runtime/blob/637e08c3f3437e5e302ec230b8c849bb61495566/packages/runtime/src/helpers/functions.ts#L254-L259
# query = { url = ":url", w = ":width", q = ":quality" }
# to = "/_ipx/w_:width,q_:quality/:url"
# status = 301


[functions]
directory = "netlify/functions"
included_files = [
  "static/**",
  # this is setup for testing regressions on EEXIST error:
  # next.config.js -> experimental.outputFileTracingIncludes makes next.js
  # to add those files to .next/standalone directory and we again add those
  # files to server handler with this configuration and this makes sure
  # there is no errors happening
  "public/**",
  # this is setup for testing regressions on EEXIST error:
  # next.js will output node_modules by default to .next/standalone
  # this makes sure we test scenario when we additionally copy extra files
  # to shared directory and make sure it's not causing EEXIST errors
  # added package is not being outputted by next.js by default
  "node_modules/js-tokens/**",
]

[images]
remote_images = [
  "https://img.etimg.com/.*",
  "https://assets.vogue.com/.*",
  "https://m.media-amazon.com/.*",
  "https://upload.wikimedia.org/.*",
  "https://premium-storefronts.s3.amazon.com/.*",
  "https://premium-storefronts.s3.amazonaws.com/.*",
  "https://teespring-storecontent.s3.amazonaws.com/.*",
  "https://vangogh.teedown.com/.*",
  "https://vangogh.teespring.com/.*",
  "https://images.teedown.com/.*",
  "https://images.teespring.com/.*",
  "https://www.paypalobjects.com/.*",
  "https://teespring-ass.s3.amazonaws.com/.*",
  "https://flagcdn.com/.*",
  "https://d1b2zzpxewkr9z.cloudfront.net/.*",
  "https://dslv9ilpbe7p1.cloudfront.net/.*",
]
